# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-04 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acuerdo',
            fields=[
                ('acuerdo_id', models.AutoField(primary_key=True, serialize=False)),
                ('acuerdo_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('acuerdo_valor', models.CharField(max_length=100, null=True)),
                ('acuerdo_fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('acuerdo_estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_nombre', models.CharField(max_length=100, null=True)),
                ('cliente_identificacion', models.CharField(max_length=16, null=True)),
                ('cliente_fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('oferta_id', models.AutoField(primary_key=True, serialize=False)),
                ('oferta_valor', models.CharField(max_length=100, null=True)),
                ('oferta_numero_producto', models.CharField(max_length=100, null=True)),
                ('oferta_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('oferta_dias_mora', models.CharField(max_length=100, null=True)),
                ('oferta_cliente_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cobranzas.Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='acuerdo',
            name='acuerdo_oferta_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cobranzas.Oferta'),
        ),
    ]
